export { default as Banner } from "./Banner";
export { default as AboutUs } from "./AboutUs";
export { default as OurServices } from "./OurServices";
export { default as Products } from "./Products";
export { default as ReachOut } from "./ReachOut";
export { default as Videos } from "./Videos";
export { default as DirectorMessage } from "./DirectorMessage";
export { default as Achievers } from "./Achievers";
export { default as Franchise } from "./Franchise";
