import React from 'react';
import {Container, Row, Col, Button} from 'reactstrap';

export default class TxPrivacyPolicy extends React.Component {
    render(){
        return(
            <Container>
                <Row>
                    <Col>
                        <div style={{fontSize:'2.5em',fontWeight:'bold',color:'#5567dd'}}>Privacy Policy</div>
                        <div style={{padding:window.matchMedia('(max-width: 600px)').matches ? '1em':'5em',textAlign:window.matchMedia('(max-width: 600px)').matches ? 'justify':''}}>
                        <p>
                            ("Teamex Retail Ltd.") is concerned about the privacy of its users (hereinafter referred to as "You" "Your" "Yourself") accessing its website located at www.teamex.in ("Website") and has provided this Privacy Policy ("Policy") to familiarise You with the manner in which Teamex Retail Ltd. collects, uses and discloses Your information collected through the Website.
                        </p>
                        <p>
                            BY USING THE WEBSITE, YOU AGREE TO THE TERMS AND CONDITIONS OF THIS POLICY. IF YOU DO NOT AGREE WITH THE TERMS AND CONDITIONS OF THIS POLICY, PLEASE DO NOT PROCEED FURTHER TO USE THIS WEBSITE. Information and Usage.
                        </p>
                        <p>
                            This Privacy Policy explains how Teamex Retail Ltd. collects personal and non-personal information, classified as mandatory or voluntary and uses, discloses and protects such information through the Website. 'Personal Information' is data that can be used to uniquely identify or contact a single person ("Personal Information"). Personal Information for the purposes of this Policy shall include, but not limited to, information regarding Your name, address, telephone number, date of birth, gender, e-mail address, etc.
                        </p>
                        <p>
                            You may need to provide Teamex Retail Ltd. Your Personal Information during the course of using some services of the Teamex Retail Ltd., for instance, creating a User ID, provide information in Your account while registering on the Website, or provide financial information while making an online purchase, upload content, participate in any online survey or contest, communicate with Teamex Retail Ltd.'s customer service by phone, email or otherwise, provide reviews for the content available on the Website.
                        </p>
                        <p>
                            Teamex Retail Ltd. collects only such Personal Information that Teamex Retail Ltd. believes to be relevant and is required to understand You or Your interests. Teamex Retail Ltd. collects Your Personal Information in order to record, support and facilitate Your participation in the activities You select, track Your preferences, to provide You with a customized Website experience, to notify You of any updated information and new activities and other related functions offered by Teamex Retail Ltd., keep You informed about latest content available on the Website, special offers, and other products and services of Teamex Retail Ltd., to assist You with customer service or technical support issues, to follow up with You after Your visit, to otherwise support Your relationship with Teamex Retail Ltd. or to prevent fraud and unlawful use.
                        </p>
                        <p>
                            In an effort to make our Website effective, certain information may be collected each time you visit the Website. Such information may be stored in server logs. These encrypted statistics do not identify you personally, but provide us the information regarding your visit to the Website and the type of user who is accessing our Website and certain browsing activities by You. This data may include: IP address of Your server from where the Website is being accessed, the type of browser (Internet Explorer, Firefox, Opera, Google Chrome etc.), the operating system of Your system and the Website You last visited before visiting to our Website. The duration of Your stay on our Website is also stored in the session along with the date and time of your access. These data are used by Teamex Retail Ltd. to understand the use and number of user visiting the Website. Some of the information related to the Website and Your visit to the Website may be shared by the sponsors, investors, advertisers, developer, strategic business partners of Teamex Retail Ltd. and some associates in order to enhance and grow our business and the Website but we assure that these information will never include any of Your Personal Informations. This anonymous information is collected through the use of a pixel tag, which is industry standard technology used by most major Websites.
                        </p>
                        <p>
                            When You use the Website, Teamex Retail Ltd. 's servers (which may be hosted by a third party service provider) may collect information indirectly and automatically about Your activities on the Website; for instance by way of cookies. A cookie is a small amount of data that is sent to a user's browser from a web server and is eventually stored on a user's computer hard drive. This anonymous information is maintained distinctly and is not linked to the Personal Information You submit to Teamex Retail Ltd.
                        </p>
                        <p>
                            Teamex Retail Ltd. DOES NOT trade or sell Your Personal Information in any manner, except as specified herein, or if express consent is sought from You.
                        </p>
                        <p>
                            Personal Information provided by You is used only:
                        </p>
                        <p>
                            To facilitate Your use of the Website;
                            To respond to Your inquiries or fulfil Your requests for information about the various services;
                            To provide You with information about Teamex Retail Ltd.'s products/services and to send You information,materials, and offers from Teamex Retail Ltd.;
                            To send You important information regarding the Website, changes to Teamex Retail Ltd.'s terms, conditions, and policies and/or other administrative information;
                            To send You surveys and marketing communications that Teamex Retail Ltd. believes may be of interest to You;
                            To personalize Your experience on the Website and Teamex Retail Ltd.'s other websites by presenting advertising, products and offers tailored to You;
                            To help You address Your problems with the Website including addressing any technical problems;
                            If You purchase any content or avail of any service from the Website, to complete and fulfil Your purchase, for example, to have Your payments processed, communicate with You regarding Your purchase and provide You with related customer service;
                            For proper administering of the Website;
                            To conduct internal reviews and data analysis for the Website (e.g., to determine the number of visitors to specific pages within the Website);
                            To improve the services, content and advertising on the Website;
                            To respond to judicial process and provide information to law enforcement agencies or in connection with an investigation on matters related to public safety, as permitted by law.
                        </p>
                        <p>
                            You acknowledge that apart from Your Personal Information, if You upload any content on the Website, such content may contain information including Personal Information and the same may be available to the other users of the Website. Teamex Retail Ltd. will not be liable for the disclosure and dissemination of such Personal Information to any third parties.
                        </p>
                        <p>Teamex Retail Ltd. may disclose aggregated information about the use of the Website, but it will never contain Personal Information. Teamex Retail Ltd. does not disclose Personal Information to third parties in the normal course of operations. However, in situations when Teamex Retail Ltd. is legally obligated to disclose information to the government or other third parties, Teamex Retail Ltd. will do so.</p>
                   <p>Teamex Retail Ltd. implements standard measures to protect against unauthorized access to and unlawful interception of Personal Information. However, no internet site can fully eliminate security risks.</p>
                   <p>Shared Personal Information You are required to submit your information at the time of making an online purchase and introduce new member on the Website. Teamex Retail Ltd. uses an online payment gateway that is operated by a third party and the information that you share with Teamex Retail Ltd. is transferred and shared with such third party payment gateway operator. The said operator may also have access to Your online purchase history/details that You make from the Website.</p>
                   <p>Extremely sensitive information like Your credit-card details are transacted upon secure sites of approved payment gateways which are digitally under encryption, thereby providing the highest possible degree of care as per current technology. You are advised, however, that internet technology is not 100% safe and You should exercise discretion on using the same.</p>
                    <p>Links to Third Party Websites The Website and any email sent to You may also contain/display third-party advertisements and links to other websites or products and services. Teamex Retail Ltd. does not provide any Personal Information to these third-party websites or agents or advertisers, however Teamex Retail Ltd. reserves the right to share with You the advertisement mailers on behalf of any other parties.</p>
                    <p>Teamex Retail Ltd. will contain links to other websites ("Linked Site") on emails sent to You and the Website which are operated by third parties and are not controlled by, or affiliated to, or associated with, Teamex Retail Ltd. unless expressly specified on the Website. Teamex Retail Ltd. is not responsible for any form of transmission, whatsoever, received by You from any Linked Site. Accordingly, Teamex Retail Ltd. does not make any representations concerning the privacy practices or policies of such third parties or terms of use of such websites, nor does Teamex Retail Ltd. control or guarantee the accuracy, integrity, or quality of the information, data, text, software, music, sound, photographs, graphics, videos, messages or other materials available on such websites. The inclusion or exclusion does not imply any endorsement by Teamex Retail Ltd. of the website, the website's provider, or the information on the website. The information provided by You to such third party websites shall be governed in accordance with the privacy policies of such websites and it is recommended that You review the privacy policy on any such websites prior to using such websites.</p>
                    <p>These third-party websites and advertisers may use technology to send the advertisements that appear on the Website directly to Your browser. In such cases, the third party websites or advertisers automatically receive Your IP address. They may also use cookies, JavaScript, web beacons and other technologies to measure the effectiveness of their advertisements and to personalize advertising content. Teamex Retail Ltd. does not have access to or control over cookies or other features that such third party websites and advertisers may use, and the information practices of these third-party websites and advertisers are not covered by this Policy. Please contact them directly for more information about their privacy practices. Security</p>
                    <p>Teamex Retail Ltd. strives to ensure the security, integrity and privacy of Your Personal Information and to protect Your Personal Information against unauthorized access or unauthorized alteration, disclosure or destruction. For this purpose, Teamex Retail Ltd. adopts internal reviews of the data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where Teamex Retail Ltd. stores Your personal data.</p>
                    <p>Teamex Retail Ltd. is not responsible for any breach of security or for any actions of any third parties that receive Your Personal Information. The Website also linked to many other sites and we are not/shall be not responsible for their privacy policies or practices as it is beyond our control.</p>
                   <p>Notwithstanding anything contained in this Policy or elsewhere, Teamex Retail Ltd. shall not be held responsible for any loss, damage or misuse of Your Personal Information, if such loss, damage or misuse is attributable to a Force Majeure Event (as defined below).</p>
                    <p>A "Force Majeure Event" shall mean any event that is beyond the reasonable control of Teamex Retail Ltd. and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, unauthorised access to computer data and storage device, computer crashes, breach of security and encryption, etc. Disclosure</p>
                   <p>Teamex Retail Ltd. will use information only in accordance with the Policy under which the information was collected unless we have received explicit authorization.</p>
                    <p>Teamex Retail Ltd. may disclose any information Teamex Retail Ltd. may have about You (including Your identity) if Teamex Retail Ltd. determines that such disclosure is necessary in connection with any investigation or complaint regarding Your use of the Website, or to identify, contact or bring legal action against someone who may be causing injury to or interference with (either intentionally or unintentionally) Teamex Retail Ltd.'s rights or property, or the rights or property of users of the Website, including Teamex Retail Ltd.'s customers. Teamex Retail Ltd. reserves the right at all times to disclose any information that Teamex Retail Ltd. deems necessary to comply with any applicable law, regulation, legal process or governmental request. Teamex Retail Ltd. also may disclose Your information when Teamex Retail Ltd. determines that applicable law requires or permits such disclosure, including exchanging information with other companies and organizations for fraud protection purposes.</p>
                    <p>You acknowledge and agree that Teamex Retail Ltd. may preserve any communication by You with Teamex Retail Ltd. through the Website or any Service, and may also disclose such data if required to do so by law or if Teamex Retail Ltd. determines that such preservation or disclosure is reasonably necessary to: (1) comply with legal process; (2) enforce this Policy; (3) respond to claims that any such data violates the rights of others; or (4) protect the rights, property or personal safety of Teamex Retail Ltd., its employees, users of, or visitors to, the Website, and the public.</p>
                    <p>User Discretion You can always choose not to provide information and in such cases, if the information required is classified as mandatory, You will not be able to avail of that part of the Services, features or content.</p>
                    <p>You can add or update Your Personal Information on a regular basis. When You update information, Teamex Retail Ltd. will keep a copy of the prior version for its records.</p>
                    <p>Teamex Retail Ltd. may, if You so choose, send direct advertisement mailers to You at the address given by You which could contain details of the products or services displayed on Teamex Retail Ltd. or of any third party not associated with Teamex Retail Ltd.. You have the option to opt-out of this direct or third party mailer by clicking at the unsubscribed link option attached to e-mail. Teamex Retail Ltd. respects Your privacy and if You do not want to receive e-mail or other communications from Teamex Retail Ltd., For any query or assistance, feel free to Contact Us.</p>
                    <p>If You do not want Teamex Retail Ltd. to use Personal Information that Teamex Retail Ltd. to You, for any query or assistance, feel free to Contact Us.</p>
                    <p>The 'Help' portion of the toolbar on most browsers will tell You how to prevent Your browser from accepting new cookies, how to have the browser notify You when You receive a new cookie, or how to disable cookies altogether. Further, You can also disable or delete similar data used by browser add-ons, such as Flash cookies, by changing the add-on's settings or visiting the Website of its manufacturer. However, as cookies allow You to take advantage of some of the Website's features, some of the Website's features and services may not function properly if Your cookies are disabled. It is therefore, recommended that You leave the cookies turned on. For instance, if You block or otherwise reject Teamex Retail Ltd.'s cookies, You will not be able to add items to Your shopping cart, proceed to checkout, or download any of Teamex Retail Ltd.'s Content or avail of Teamex Retail Ltd.'s services that require You to log in. General Provisions By accessing the Website, You have agreed to the terms set out in this Policy. This Policy should be at all times read along with the Terms of Use of the Website.</p>
                   <p>Unless stated otherwise, the Policy applies to all information that Teamex Retail Ltd. has about You and Your account.</p>
                    <p>By using this Website and the products, content and services provided on the Website, You agree and acknowledge that Your Personal Information collected through the Website may be transferred across national boundaries and stored and processed in any the country around the world. You also acknowledge that in certain countries or with respect to certain activities, the collection, transfer, storage, and processing of Your information may be undertaken by trusted third party vendors or agents of Teamex Retail Ltd. such as credit card processors, web hosting providers, communication services, and web analytic providers, to help facilitate Teamex Retail Ltd. in providing certain functions.</p>
                   <p>Teamex Retail Ltd. may make changes to this Policy, from time to time at Teamex Retail Ltd.'s sole discretion or on account of changes in law. Teamex Retail Ltd. will not reduce Your rights under this Policy without Your explicit consent. Teamex Retail Ltd. may e-mail periodic reminders of the notices and conditions, unless You have instructed Teamex Retail Ltd. not to, but You should check the Website frequently to see recent changes. Notwithstanding the above, Teamex Retail Ltd. shall not be required to notify You of any changes made to the Policy. The revised Policy shall be made available on the Website. Your continued use of the Website, following changes to the Policy, will constitute Your acceptance of those changes.</p>
                    <p>If You choose to visit the Website, Your visit and any dispute over privacy is subject to this Policy and the Website's Terms of Use. In addition to the foregoing, any disputes arising under this Policy shall be governed by the laws of India.</p>
                    <p>Grievance Officer
                        In accordance with Information Technology Act 2000 and rules made there under, the name and contact details can be contacted with respect to any complaints or concerns including those pertaining to breach of Teamex Retail Ltd.’s Terms of Use, Term of Offer For Sale and other polices or questions are published as under:of the Grievance Officer who
                    </p>
                        <p>Grievance Officer Name: Pratap Pansuria
                            Phone No: 079-22770377
                            email address: info@teamex.in
                        </p>
                        </div>
                    </Col>
                </Row>
            </Container>
        )
    }
}
